### ISSUE TITLE
Add optional support for Datadog extensions?

### ISSUE THREAD

**Issue by robinst** [tshlabs/cadence#40]
[Datadog](https://www.datadoghq.com/) is a popular implementation of statsd, and it adds some useful extensions on top of the statsd protocol.

One of them is [histograms](http://docs.datadoghq.com/guides/dogstatsd/#histograms). As can be seen [here](https://github.com/DataDog/datadogpy/blob/master/datadog/dogstatsd/base.py#L166) the type for a histogram is `h`.

It looks like this library is extensible enough to allow adding these myself by implementing `Metric` (if I read the sources correctly).

Having said that, I wanted to see if you already thought about adding them to the library or what your thoughts are about the Datadog extensions.

**Comment by robinst** [comment]
> to allow adding these myself by implementing Metric (if I read the sources correctly)

Computer says no:

```
error: module `types` is private
 --> src/handler.rs:9:5
  |
9 | use cadence::types::Metric;
  |     ^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by 56quarters** [comment]
Hi @robinst 

I'm only vaguely familiar with Datadog and their extensions to Statsd. Histograms look useful and they would probably be very straightforward to add support for. I can open a PR and cc you there if that works for you. Thanks!

**Comment by robinst** [comment]
Sounds good!

Histograms also in the spec you linked in the code, so maybe more implementations support it: https://github.com/b/statsd_spec/blob/master/README.md#histograms

Another useful thing is tags, which allow you to attach more information to a metric, see here: http://docs.datadoghq.com/guides/dogstatsd/#tags

The format is described later in the page under "Datagram Format".

**Comment by 56quarters** [comment]
Cool.

I'll open another issue for tag support since they'll be a bit more work and I'd like to think about how I'd implement them. Thanks again!

**Comment by 56quarters** [comment]
PR for histogram support #42. The docs related to the new trait are my interpretation of the [Datadog](http://docs.datadoghq.com/guides/dogstatsd/#histograms) docs as well as the [Statsd](https://github.com/b/statsd_spec) spec. Let me know if I've gotten anything wrong.

**Comment by 56quarters** [comment]
Thanks @robinst! I'll probably end up cutting version 0.9.0 with this change in the next few weeks.

**Comment by robinst** [comment]
Cool, thanks! No rush by the way, I'll check out the release in the new year.
