### ISSUE TITLE
Add `time` method taking `Duration` in `Timed` trait?

### ISSUE THREAD

**Issue by robinst** [tshlabs/cadence#48]
Using `time` to record a timing, I've found myself having to write this to convert a [`Duration`](https://doc.rust-lang.org/std/time/struct.Duration.html) to milliseconds like this:

```
let start = Instant::now();
...
let duration = start.elapsed();
let ms = (duration.as_secs() * 1_000) + (duration.subsec_nanos() / 1_000_000) as u64;
```

Note that this can overflow. I decided to not care about this because this is about metrics (and if your timing overflows, your app has a bigger problem than incorrect metrics).

I wonder if you've considered adding an additional method to `Timed` that takes a `Duration` instead of a `u64` and handles the conversion? It could return `Err` in case of overflow.

**Comment by 56quarters** [comment]
I hadn't thought of it but that's a great idea. Any ideas for the potential new method name in `Timed`?

**Comment by robinst** [comment]
If you're ok with a breaking change, you could consider renaming the existing one to `time_millis` to make it really explicit what it is taking.

If not, the new one could be named `time_duration`.

**Comment by 56quarters** [comment]
I'd rather not make people change working code. I think `time_duration` sounds good, thanks!

**Comment by 56quarters** [comment]
Opened #55 to address this. Let me know what you think!

**Comment by robinst** [comment]
Thanks for notifying, went through the change and it looks good!
