### ISSUE TITLE
Add sampling support

### ISSUE THREAD

**Issue by 56quarters** [tshlabs/cadence#6]
The client doesn't currently support sampling. Sampling allows callers to submit a metric every Nth time instead of every time (potentially for performance reasons). Cadence doesn't support this currently because adding a floating points to metric structs broke Eq (I think, can't quite remember). Let's fix this.

**Comment by 56quarters** [comment]
Closing until there's an actual for this.

**Comment by pmembrey** [comment]
Is there any potential to look at implementing this feature? I use `statsd` in a high performance app where metrics can be taken on every network read and write (providing a measure of throughput). I wouldn't want to actually send one stats message every time I read or write to a socket, so for me, sampling is essential.

Happy to help in any way I can to get support for this feature, including potentially a bounty if anyone is free to work on it 😄

**Comment by 56quarters** [comment]
I think I conflated two different ways of doing sampling in original description.

There are two ways I imagine sampling could work:
* Add `@0.1` to the text format of each metric sent, as described [here](https://github.com/b/statsd_spec). Letting the server deal with the sampling.
* Only actually send 10% of measurements to the server, doing a `if rand(100) % 10 == 0 { send(); }`.

If the concern however is performance, there are other options (apologies if you've already looked into these):
* Cadence can buffer metrics via `BufferedUdpMetricSink` so you aren't sending N UDP packets for every metric
* You could keep a counter in your application and only periodically send the accumulated value via Cadence.

Could you open a new issue with what you're looking for and we can discuss there?
