### ISSUE TITLE
Consider adding #[must_use] to MetricBuilder

### ISSUE THREAD

**Issue by robinst** [tshlabs/cadence#63]
I just updated my code to make use of tags (thanks for adding it, works great!). Now I have this code for example:

```rust
client.mark_with_tags("metric")
    .with_tag("key", "value")
    .send()
    .ok();
```

One thing that came up in the review was that it's easy to forget to call `.send()` on the `MetricBuilder`. And if you do, there's no warning.

So I was wondering, have you considered annotating `MetricBuilder` with `#[must_use]`? I gave it a quick try locally and it seems to work nicely, it results in a warning like this:

> warning: unused `cadence::builder::MetricBuilder` which must be used

It prints that warning if you just have a `mark_with_tags(...)` and even when you have `mark_with_tags(...).with_tag(...)` (but forgot `send`).

**Comment by 56quarters** [comment]
Great catch! I'll add this soon

**Comment by robinst** [comment]
That was quick :). Thanks!

While we have the example in the description, have you considered adding an alternative to the `send` method that ignores any errors instead of returning a result? Currently, not calling `.ok()` on the `Result` results in a warning.

**Comment by 56quarters** [comment]
That method could be added. What do you think a good name would be? `send_quiet()`?

**Comment by 56quarters** [comment]
I've opened #65 for the method that ignores the results and doesn't require calling `.ok()` on the result of `.send()`
