### ISSUE TITLE
Automatically add tags to all metrics

### ISSUE THREAD

**Issue by Diggsey** [tshlabs/cadence#67]
It would be useful to be able to create a new "view" on a `StatsdClient` which automatically adds tags to all metrics reported through that client.

If I have multiple workers within an application, or multiple instances of that application running at the same time, the "metric reporting code" currently needs to know the application/worker IDs to add the correct tags.

**Comment by Diggsey** [comment]
@56quarters Ideally I would be able to create a new `StatsdClient` based on existing one plus some extra tags, so that I could layer tags.

For example, in my current application I have implemented this functionality as a new type, `StatsdView`. In the `main` function I create a `StatsdView` which adds the tag `pod_name`, which identifies kubernetes pod in which the application is running. Then, each worker thread within the application creates its own `StatsdView` from that, also adding the `worker_id` tag. The `pod_name` + `worker_id` pair now uniquely identify a worker thread within our entire kubernetes cluster.

**Comment by 56quarters** [comment]
I'll try to see if it's reasonable to implement something like this as something in the `examples` directory. Maybe it's possible provide this functionality without any library changes.

**Comment by 56quarters** [comment]
I've added an example of the pattern you described (I think, let me know if I got something wrong) in #76. This doesn't add the functionality to Cadence itself, just the examples directory. I think it's enough to have an example to be able to point to for this kind of problem.
